export const fetchMockJSON = () => {
      return [
        {
          id: "101",
          type: "solar",
          price: 110,
          minimumQuantity: 100,
          contractTerms: "2 years",
          paymentTerms: "Credit card",
          capacity: 500,
          location: "Seville, Spain",
          certifications: ["REC"],
          energyOutputPredictions: [450, 470, 480],
          timeOfAvailability: ["08:00-18:00"],
          confirmed: false,
        },
        {
          id: "102",
          type: "gas",
          price: 130,
          minimumQuantity: 200,
          contractTerms: "3 years",
          paymentTerms: "Wire transfer",
          capacity: 1000,
          location: "Texas, USA",
          deliveryMethod: "pipeline",
          flexibilityOfSupply: "High",
          emissionCredits: -200,
          contractLength: "3 years",
          confirmed: false,
        },
        {
          id: "103",
          type: "wind",
          price: 95,
          minimumQuantity: 150,
          contractTerms: "1 year",
          paymentTerms: "Wire transfer",
          capacity: 750,
          location: "Patagonia, Argentina",
          windSpeedPredictions: [15, 18, 20],
          turbineEfficiency: 0.87,
          timeOfAvailability: ["Variable"],
          certifications: ["REC"],
          confirmed: false,
        },
        {
          id: "104",
          type: "hydro",
          price: 105,
          minimumQuantity: 250,
          contractTerms: "4 years",
          paymentTerms: "Bank transfer",
          capacity: 1200,
          location: "Norway",
          waterFlowRate: 300,
          reservoirLevel: 80,
          regulatoryCompliance: "OK",
          flexibilityOfSupply: "Medium",
          storageCapacity: 500,
          confirmed: false,
        },
        {
          id: "105",
          type: "thermal",
          price: 130,
          minimumQuantity: 300,
          contractTerms: "5 years",
          paymentTerms: "Wire transfer",
          capacity: 1000,
          location: "Iceland",
          heatSourceStability: "High",
          temperatureGradient: 120,
          conversionEfficiency: 0.65,
          environmentalImpact: "Low",
          confirmed: false,
        },
        {
          id: "106",
          type: "kinetic",
          price: 90,
          minimumQuantity: 50,
          contractTerms: "1 year",
          paymentTerms: "Credit card",
          capacity: 100,
          location: "Tokyo, Japan",
          energyConversionEfficiency: 0.4,
          predictabilityOfSource: "High foot traffic",
          confirmed: false,
        },
        {
          id: "107",
          type: "solar",
          price: 115,
          minimumQuantity: 120,
          contractTerms: "2 years",
          paymentTerms: "Wire transfer",
          capacity: 520,
          location: "Madrid, Spain",
          certifications: ["REC"],
          energyOutputPredictions: [460, 480, 495],
          timeOfAvailability: ["08:00-19:00"],
          confirmed: false,
        },
        {
          id: "108",
          type: "wind",
          price: 98,
          minimumQuantity: 180,
          contractTerms: "1 year",
          paymentTerms: "Bank transfer",
          capacity: 800,
          location: "Scotland, UK",
          windSpeedPredictions: [12, 15, 18],
          turbineEfficiency: 0.9,
          timeOfAvailability: ["Variable"],
          certifications: ["REC"],
          confirmed: false,
        },
        {
          id: "109",
          type: "hydro",
          price: 110,
          minimumQuantity: 200,
          contractTerms: "3 years",
          paymentTerms: "Wire transfer",
          capacity: 1300,
          location: "Brazil",
          waterFlowRate: 350,
          reservoirLevel: 90,
          regulatoryCompliance: "OK",
          supplyFlexibility: "High",
          storageCapacity: 600,
          confirmed: false,
        },
        {
          id: "110",
          type: "thermal",
          price: 140,
          minimumQuantity: 320,
          contractTerms: "5 years",
          paymentTerms: "Credit card",
          capacity: 1100,
          location: "Chile",
          heatSourceStability: "Medium",
          temperatureGradient: 110,
          conversionEfficiency: 0.7,
          environmentalImpact: "Medium",
          confirmed: false,
        },
      ];
  };